### ISSUE TITLE
Inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by scneba** [victronenergy/vrm-api-python-client#2]
Having issues with inconsistent spacing in some  `_send_query_request` function calls. I think spaces before closing brackets could be elimited. 

`Traceback (most recent call last):

  File "/home/clasence/miniconda3/envs/aws/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-45-45996bec58db>", line 2, in <module>
    from vrmapi.vrm import VRM_API

  File "/home/clasence/miniconda3/envs/aws/lib/python3.7/site-packages/vrmapi/vrm.py", line 169
    stats = self._send_query_request(request_url, data_dict=data_dict  )
                                                                                                               ^
TabError: inconsistent use of tabs and spaces in indentation`

**Comment by thlassche** [comment]
Hi @scneba,

I just pushed a fix for the issues you mention
