### ISSUE TITLE
Indentation error

### ISSUE THREAD

**Issue by philippweder** [victronenergy/vrm-api-python-client#7]
I tried to run the code example to access the API with python. Unfortunately, I have run into the following problem: Executing the command
`from vrmapi.vrm import VRM_API`
leads to this error message
```
Traceback (most recent call last):

  File "/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-88-38481c48a19a>", line 1, in <module>
    from vrmapi.vrm import VRM_API

  File "/opt/conda/lib/python3.8/site-packages/vrmapi/vrm.py", line 169
    stats = self._send_query_request(request_url, data_dict=data_dict )
                                                                       ^
TabError: inconsistent use of tabs and spaces in indentation
```

So, apparently, there is an indentation problem in the code.

**Comment by photon-delight** [comment]
I experienced the same problem.. it can be fixed by cleaning up the indentation in 

`def get_diag` method
